services:
  taskmanagement.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:8080"
    depends_on:
      - taskmanagement.reverseproxy
    networks:
      - app-network
      
  taskmanagement.reverseproxy:
    ports:
      - "5000:8080"
    depends_on:
      - usermanagement.api
      - taskmanagement.api
      - projectmanagement.api
    networks:
      - app-network
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys

  usermanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
    networks:
      - app-network

  taskmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:8080"
    networks:
      - app-network

  projectmanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:8080"
    networks:
      - app-network

networks:
  app-network:
    name: proxy-network
    driver: bridge

volumes:
  dataprotection-keys:
